# Date: 6/30/2025
# Calculate the factorial of a number


# print("Output the sequence generated by range function\n")
# sum = 0
# for k in range(14, 1,3):
#     print("k= ",k)
#     sum = sum + k
#     print("sum = ",sum)
#     print("------------------")
    
mul = 1
for t in range(1, 3):
    print("mul = ",mul)
    print("mul = ",mul)
    
    print("------------------")
    
print("mul = ",mul)
print("mul = ",mul)
    
# for i in range(10, 1,-2):
#     print(" ",i)


# num = [1, 2]
# fruits = ["Apple", "Banana"]
# for x in num:
#     for y in fruits:
#         print(x, y)   
        
# for i in range(1,3):
#     for j in range(1,3):
#         print(i, j)   



# #print("Output the sequence generated by a list")
# courses = ["java", "python", "pandas"]
# for i in courses:
#     print(i) 
#     print(i)

# sum = 0
# for i in range(1,101):
#     sum = sum + i
    
# print("sum of 1 to 100 is :", sum)    

# # Initialize the factorial value
# factorial = 1
#  # 4! =1 * 2 * 3 * 4
# for i in range(1, 4):
#     factorial = factorial * i
#     print(" i = " ,i, ", factorial = ",factorial)   

#Practice:  calcuate the sum of the squence 1,2,...,100
    

print("----------------------\n")
#print("The factorial of", num, "is", factorial)


